# Setup
title: "Dennis I. Barrett"
tagline: "programming • math • data"
description: ""
url: "https://www.dennisbarrett.co.za"
imgurl: "/public/img"
# paginate: 3
permalink: pretty

# About/contact
author:
  name: Dennis I. Barrett
  url: https://www.linkedin.com/in/dr-di-barrett/
  email: dbarrett6@gmail.com

# Gems
plugins:
  - jekyll-paginate-v2
  - jekyll-toc

# Pagination settings
pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 10
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "blog"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: "index"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Custom vars
version: 1.1.0
google_analytics_id: G-TX2WTGL5FG
