# Setup
title:               'Dennis I. Barrett'
tagline:             'programming • math • data'
description:         ''
url:                 'https://www.dennisbarrett.co.za'
imgurl:              '/public/img'
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Dennis I. Barrett
  url:               https://www.linkedin.com/in/dr-di-barrett/
  email:             dbarrett6@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-toc

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
